services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  server:
    image: server
    ports:
      - "3000:3000"
volumes:
  dbdata:
